// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/provers/ibft2/config/config.proto

package module

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProverConfig struct {
	TrustLevelNumerator   uint32 `protobuf:"varint,1,opt,name=trust_level_numerator,json=trustLevelNumerator,proto3" json:"trust_level_numerator,omitempty"`
	TrustLevelDenominator uint32 `protobuf:"varint,2,opt,name=trust_level_denominator,json=trustLevelDenominator,proto3" json:"trust_level_denominator,omitempty"`
	TrustingPeriod        uint64 `protobuf:"varint,3,opt,name=trusting_period,json=trustingPeriod,proto3" json:"trusting_period,omitempty"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_912b2ba2cd96b01e, []int{0}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProverConfig)(nil), "relayer.provers.ibft2.config.ProverConfig")
}

func init() {
	proto.RegisterFile("relayer/provers/ibft2/config/config.proto", fileDescriptor_912b2ba2cd96b01e)
}

var fileDescriptor_912b2ba2cd96b01e = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe3, 0xef, 0x43, 0x0c, 0x11, 0x3f, 0x52, 0xa0, 0xa2, 0x54, 0xc8, 0xaa, 0x58, 0x28,
	0x43, 0x63, 0x51, 0x24, 0x2e, 0x00, 0x18, 0x11, 0x54, 0x1d, 0x59, 0x22, 0x27, 0x71, 0x5c, 0x4b,
	0x8e, 0x4f, 0xe4, 0x3a, 0x95, 0x7a, 0x17, 0xdc, 0x03, 0x37, 0xd3, 0xb1, 0x23, 0x23, 0x24, 0x37,
	0x82, 0x7a, 0x9c, 0xaa, 0x4c, 0xb6, 0xcf, 0xf3, 0x3e, 0x47, 0xf2, 0x1b, 0xde, 0x5a, 0xa1, 0xf9,
	0x4a, 0x58, 0x56, 0x59, 0x58, 0x0a, 0xbb, 0x60, 0x2a, 0x2d, 0xdc, 0x84, 0x65, 0x60, 0x0a, 0x25,
	0xbb, 0x23, 0xae, 0x2c, 0x38, 0x88, 0xae, 0xba, 0x68, 0xdc, 0x45, 0x63, 0x8c, 0xc6, 0x3e, 0x33,
	0x38, 0x97, 0x20, 0x01, 0x83, 0x6c, 0x7b, 0xf3, 0xce, 0xe0, 0x52, 0x02, 0x48, 0x2d, 0x18, 0xbe,
	0xd2, 0xba, 0x60, 0xdc, 0xac, 0x3c, 0xba, 0xfe, 0x24, 0xe1, 0xd1, 0x14, 0x37, 0x3d, 0xe1, 0x86,
	0x68, 0x12, 0xf6, 0x9c, 0xad, 0x17, 0x2e, 0xd1, 0x62, 0x29, 0x74, 0x62, 0xea, 0x52, 0x58, 0xee,
	0xc0, 0xf6, 0xc9, 0x90, 0x8c, 0x8e, 0x67, 0x67, 0x08, 0x5f, 0xb6, 0xec, 0x75, 0x87, 0xa2, 0x87,
	0xf0, 0xe2, 0xaf, 0x93, 0x0b, 0x03, 0xa5, 0x32, 0x68, 0xfd, 0x43, 0xab, 0xb7, 0xb7, 0x9e, 0xf7,
	0x30, 0xba, 0x09, 0x4f, 0x11, 0x28, 0x23, 0x93, 0x4a, 0x58, 0x05, 0x79, 0xff, 0xff, 0x90, 0x8c,
	0x0e, 0x66, 0x27, 0xbb, 0xf1, 0x14, 0xa7, 0x8f, 0x6f, 0xeb, 0x1f, 0x1a, 0xac, 0x1b, 0x4a, 0x36,
	0x0d, 0x25, 0xdf, 0x0d, 0x25, 0x1f, 0x2d, 0x0d, 0x36, 0x2d, 0x0d, 0xbe, 0x5a, 0x1a, 0xbc, 0xdf,
	0x49, 0xe5, 0xe6, 0x75, 0x1a, 0x67, 0x50, 0xb2, 0x9c, 0x3b, 0x9e, 0xcd, 0xb9, 0x32, 0x9a, 0xa7,
	0xbe, 0xc5, 0x31, 0x16, 0x36, 0xf6, 0x75, 0xb1, 0x12, 0xf2, 0x5a, 0x8b, 0xf4, 0x10, 0x7f, 0x7f,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xec, 0xa7, 0x5e, 0x79, 0x01, 0x00, 0x00,
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TrustingPeriod != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.TrustingPeriod))
		i--
		dAtA[i] = 0x18
	}
	if m.TrustLevelDenominator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.TrustLevelDenominator))
		i--
		dAtA[i] = 0x10
	}
	if m.TrustLevelNumerator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.TrustLevelNumerator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustLevelNumerator != 0 {
		n += 1 + sovConfig(uint64(m.TrustLevelNumerator))
	}
	if m.TrustLevelDenominator != 0 {
		n += 1 + sovConfig(uint64(m.TrustLevelDenominator))
	}
	if m.TrustingPeriod != 0 {
		n += 1 + sovConfig(uint64(m.TrustingPeriod))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevelNumerator", wireType)
			}
			m.TrustLevelNumerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustLevelNumerator |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevelDenominator", wireType)
			}
			m.TrustLevelDenominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustLevelDenominator |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			m.TrustingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustingPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
