#!/bin/bash

set -eux

retry() {
    local -r -i max_attempts="$1"; shift
    local -r cmd="$@"
    local -i attempt_num=1

    until $cmd
    do
        if (( attempt_num == max_attempts ))
        then
            echo "Attempt $attempt_num failed and there are no more attempts left!"
            return 1
        else
            echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..."
            sleep $(( attempt_num++ ))
        fi
    done
}

RLY="${RLY_BIN} --debug"
PATH_NAME=ibc01

retry 5 $RLY tx clients $PATH_NAME
retry 5 $RLY tx connection $PATH_NAME -o 2s
retry 5 $RLY tx channel $PATH_NAME -o 2s
