#!/bin/bash
set -eux

RLY="${RLY_BIN} --debug"
TEST_DIR=$(dirname $(dirname $(dirname "$0")))

source ${TEST_DIR}/chain0.env.sh
npx hardhat --network chain0 send-packet \
    --mockapp ${IBC_MOCKAPP} \
    --message "mock packet data" \
    --port mockapp \
    --channel channel-0 \
    --timeoutheight 1000000000

sleep 4
${RLY} tx relay ibc01
sleep 4
${RLY} tx acks ibc01
